# Generated by Django 4.2.7 on 2023-11-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_users_model',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_Profile', models.FileField(upload_to='images/')),
                ('User_Email', models.EmailField(max_length=50)),
                ('User_Status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'all_users',
            },
        ),
        migrations.CreateModel(
            name='Upload_dataset_model',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Dataset', models.FileField(null=True, upload_to='')),
                ('File_size', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'upload_dataset',
            },
        ),
    ]
